### ISSUE TITLE
How does `setCurrentScreenName` actually work?

### ISSUE THREAD

**Issue by gsantiago** [microsoft/clarity-apps#27]
My records only show that they have one screen: `MainActivity`. Is it correct or it should show all the screens that my `setCurrentScreenName` called?

In the heat maps, I can see my custom screen names when I toggle the "Components" switch. Then it shows the screens like this: `MainActivity/Home`, `MainActivity/Product`, etc.

So, is it correct or am I doing something wrong?

**Comment by ibradwan** [comment]
Hi @gsantiago,

Whenever you set the current screen name, it will be registered as a UI Component the belongs to the current screen (in your case it's called MainActivity). For single screen apps (like ReactNative), you should primarily focus on Components rather than screens to get the best insights.

Now if you would like to filter on a certain component you can do the following for each scenario:

**Dashboard**:
  - To see the popular Components (i.e., ReactNative screens), you should enable the Components toggle here:
<img width="359" alt="image" src="https://github.com/microsoft/clarity-apps/assets/67283130/81a46008-ce7b-428c-9d85-1be1467ac600">

  - To filter the analytics on the sessions that have a certain Component, you should use this filter:
 
<img width="983" alt="image" src="https://github.com/microsoft/clarity-apps/assets/67283130/ba663566-0371-4731-a378-8714e056871a">

**Heatmaps**:
As you've already seen, you can toggle on Components and this will allow you to get their heatmaps:
<img width="1771" alt="image" src="https://github.com/microsoft/clarity-apps/assets/67283130/b10c8dfa-ae3b-4c7c-9470-af74a38ee31d">

**Recordings**:
You can use the same filter mentioned above to filter on the sessions that have these components visible.

**Comment by gsantiago** [comment]
@ibradwan thank you very much! It's much clear now!

**Comment by khanh21011999** [comment]
Hi @ibradwan , thank for your answer but still have some question, in our react native application, i always see it as `MainActivity` in the recording
In heatmap i can see custom screen name like 'MainActivity/LoginScreen"...etc
But do we possible show the current react-native screen on the recording?  Since everyscreen in recording is MainActivity, then easier to track

**Comment by ibradwan** [comment]
@khanh21011999 Yes, that's exactly what the `setCurrentScreenName` function does. Could you please follow the example in the [package readme](https://www.npmjs.com/package/react-native-clarity) and see if this solves your problem?
